language: node_js

node_js:
  - node
  - lts/*

install:
  - npm install

script:
  # We want to run as root so manipulating file permissions etc works
  # ... but travis installs npm locally to the user 'travis' rather
  # that into root's PATH, -E preserves current user's environement variables
  - sudo -E env "PATH=$PATH" npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
